version: "3.9"

services:
  api:
    build: .
    container_name: capsbank_api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn caps_bank.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"

  db:
    image: postgres:15
    container_name: capsbank_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: capsbank_redis
    restart: always

  celery:
    build: .
    container_name: capsbank_celery
    command: celery -A caps_bank worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - db

  celery-beat:
    build: .
    container_name: capsbank_celery_beat
    command: celery -A caps_bank beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api
      - redis
      - db

  nginx:
    image: nginx:latest
    container_name: capsbank_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
