version: "3.9"

services:
  api:
    build: .
    container_name: capsbank_api
    command: gunicorn caps_bank.wsgi:application --bind 0.0.0.0:8000 --workers 4
    env_file: .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    expose:
      - "8000"

  celery:
    build: .
    container_name: capsbank_celery
    command: ["celery"]
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api

  celery-beat:
    build: .
    container_name: capsbank_celery_beat
    command: ["celery-beat"]
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api

  db:
    image: postgres:15
    container_name: capsbank_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: capsbank_redis
    restart: always
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: capsbank_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
