version: "3.9"

services:
  api:
    build: .
    container_name: capsbank_api
    command: "api"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 5s
      retries: 10

  celery:
    build: .
    container_name: capsbank_celery
    command: "celery"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api

  celery-beat:
    build: .
    container_name: capsbank_celery_beat
    command: "celery-beat"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - api

  db:
    image: postgres:15
    container_name: capsbank_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: capsbank_redis
    restart: always

  nginx:
    image: nginx:latest
    container_name: capsbank_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume:
