api:
  build: .
  container_name: capsbank_api
  volumes:
    - .:/app
    - static_volume:/app/static
    - media_volume:/app/media
  env_file:
    - .env
  depends_on:
    - db
    - redis
  expose:
    - "8000"

celery:
  build: .
  container_name: capsbank_celery
  command: celery -A caps_bank worker -l info
  volumes:
    - .:/app
  env_file:
    - .env
  depends_on:
    - db
    - redis
    - api

celery-beat:
  build: .
  container_name: capsbank_celery_beat
  command: celery -A caps_bank beat -l info
  volumes:
    - .:/app
  env_file:
    - .env
  depends_on:
    - db
    - redis
    - api
